"""empty message

Revision ID: 013d6883cd0e
Revises: 
Create Date: 2019-05-17 17:49:13.428046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013d6883cd0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.Column('classification', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classification'], ['classification.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('classification')
    # ### end Alembic commands ###
