"""empty message

Revision ID: 185a60f34b37
Revises: 639bbed78c9c
Create Date: 2019-05-18 16:11:02.893468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185a60f34b37'
down_revision = '639bbed78c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('Keyword', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'Keyword')
    # ### end Alembic commands ###
