"""empty message

Revision ID: 6a54be5d8a29
Revises: a6af13750c3a
Create Date: 2019-05-20 17:52:37.520847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a54be5d8a29'
down_revision = 'a6af13750c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification', sa.Column('num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classification', 'num')
    # ### end Alembic commands ###
