"""empty message

Revision ID: 784360979bbf
Revises: a62bc1e9dbbe
Create Date: 2019-05-18 09:43:40.123974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784360979bbf'
down_revision = 'a62bc1e9dbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('comment', sa.Integer(), nullable=True))
    op.add_column('article', sa.Column('data', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'data')
    op.drop_column('article', 'comment')
    # ### end Alembic commands ###
