"""empty message

Revision ID: 86b6c7f45f1e
Revises: 013d6883cd0e
Create Date: 2019-05-17 21:22:49.321719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86b6c7f45f1e'
down_revision = '013d6883cd0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'imgsrc',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'无'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('article', 'imgsrc',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'无'"))
    # ### end Alembic commands ###
