"""empty message

Revision ID: a62bc1e9dbbe
Revises: 86b6c7f45f1e
Create Date: 2019-05-18 09:30:29.840601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62bc1e9dbbe'
down_revision = '86b6c7f45f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('label', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'label')
    # ### end Alembic commands ###
