"""empty message

Revision ID: a6af13750c3a
Revises: 185a60f34b37
Create Date: 2019-05-20 17:32:55.705995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6af13750c3a'
down_revision = '185a60f34b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification', sa.Column('alias', sa.String(length=20), nullable=True))
    op.add_column('classification', sa.Column('content', sa.String(length=1000), nullable=True))
    op.add_column('classification', sa.Column('keyword', sa.String(length=20), nullable=True))
    op.add_column('classification', sa.Column('parentnode', sa.String(length=20), nullable=True))
    op.drop_column('classification', 'num')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification', sa.Column('num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('classification', 'parentnode')
    op.drop_column('classification', 'keyword')
    op.drop_column('classification', 'content')
    op.drop_column('classification', 'alias')
    # ### end Alembic commands ###
